### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by igororlov** [nnethercote/counts#1]
When running `cargo build --release` inside the "counts" folder, I get the following error:
```
error[E0658]: `dyn Trait` syntax is unstable (see issue #44662)
  --> src/main.rs:14:30
   |
14 |     let mut readers: Vec<Box<dyn BufRead>> = vec![];
   |                              ^^^^^^^^^^^

error: aborting due to previous error
```

My cargo version is 0.26.0.

**Comment by nnethercote** [comment]
Thanks for the report. The `dyn Trait` syntax was added in Rust 1.27: https://blog.rust-lang.org/2018/06/21/Rust-1.27.html

I will update the docs tomorrow to note that 1.27 is the minimum version.

**Comment by nnethercote** [comment]
I added the documentation in https://github.com/nnethercote/counts/commit/cfc68d5cf6ff0e980c098391958a1c734451ddf2.
