### ISSUE TITLE
in AWK we trust

### ISSUE THREAD

**Issue by setop** [nnethercote/counts#5]
Hi,

Interesting tool and use case.

Being AWK enthusiast, I could not resist replicate the use case with it.

`{ A[$1]+=$2 } END { for (a in A) { print a, A[a] }} | sort -n -r -k2` is roughly equivalent to `counts -i -e`

On a 4+ millions records file, 20MB size, in RAM, awk process it in 0.55 seconds, counts in 2.30 seconds on my laptop, ~4x faster.

For sure it will require more than this one-liner to achieve the pretty formatting of the result that `counts` proposes. Plus if you wanna study Rust, it's very off-topic. Still, AWK is stunning to me.

Cheers

**Comment by nnethercote** [comment]
Interesting info. But no action to be taken here.

**Comment by setop** [comment]
[mawk](https://invisible-island.net/mawk/), the AWK's implementation I used here, is using an interpreted bytecode and Rust is compiled to native with a lot of optimizations, the speed advantage should be on `counts` side for this aspect.

I've seen in the code you [questioned the data structure](https://github.com/nnethercote/counts/blob/2cb292aabbef775fec195d06e4391516de7139d6/src/main.rs#L6). Maybe the different is one that side.
