### ISSUE TITLE
Ignore timestamps

### ISSUE THREAD

**Issue by frakman1** [nnethercote/counts#6]
I would like to run `counts` on my log files and observe any patterns that emerge. However, each line includes a timestamp that makes it technically unique, despite the actual log contents being otherwise identical.

Is there a way to somehow ignore the timestamp part of the line when running `counts`?

e.g.:
`modulename: <thread or function name> 19:03:54.866: actual log line`
...
`modulename: <thread or function name> 19:03:59.185: actual log line`

Note in the example above, the two lines are identical except for the embedded timestamp.

Also, what about the case where you just want to ignore a unique line prefix in case the timestamp or an integer is changing there?

**Comment by setop** [comment]
@frakman1, in #5, I pointed out that AWK can be used. It is more flexible as it is a language. You could use it to count on the field(s) you want, not considering others.

**Comment by nnethercote** [comment]
`counts` has no way to ignore a timestamp. I suggest piping your input through some kind of filter like `sed` before feeding it into `counts`. That's a lot more flexible than building this kind of function into `counts` itself.
