### ISSUE TITLE
Crashes on invalid UTF-8

### ISSUE THREAD

**Issue by connorskees** [nnethercote/counts#7]
`counts` will crash with the following error when piped random bytes:

![image](https://github.com/nnethercote/counts/assets/39542938/d60886ef-9763-40f9-ab36-ca23b921e116)

This can be reproduced by just running `counts name_of_binary_file`. 

I don't have a strong opinion on the correct behavior, and you may not even consider this a bug, but I thought it would be useful to open an issue. I think at the very least printing an error message rather than crashing would be an improvement.

Ideally `counts` would either ignore lines containing invalid UTF-8, or would not require UTF-8 and operate on byte slices (still printing strings, similar to the debug output of [`bstr`](https://docs.rs/bstr/latest/bstr/) or [`Path`](https://doc.rust-lang.org/stable/std/path/struct.Path.html)).

My use case is that sometimes I accidentally pass invalid UTF-8 to `counts`, and it crashing means I have to restart the potentially lengthy execution. It happens infrequently and due to a mistake on my part, so I don't have strong thoughts on the best solution here.

**Comment by nnethercote** [comment]
Thanks for the report. I decided to just abort with `error: non-UTF-8 input detected` in this case.

**Comment by nnethercote** [comment]
Fix is in 1.0.2, just released.
